//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIVO.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class OrderDetail
    {
        [DisplayName("เลขที่การขาย")]
        public string Order_Id { get; set; }
        [DisplayName("รหัสสินค้า")]
        public string Pro_Id { get; set; }
        [DisplayName("จำนวน")]
        public int OrderDetails_Number { get; set; }
        [DisplayName("ราคา")]
        public decimal Pro_Price { get; set; }


        public virtual Product Product { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
    }
}
